<?php

use Illuminate\Database\Seeder;

class LogWalletTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('log_wallet')->delete();
        
        \DB::table('log_wallet')->insert(array (
            0 => 
            array (
                'id' => 1,
                'wallet_type_log' => 'created',
                'wallet_type' => 1,
                'wallet_user_id' => 1,
                'wallet_user_name' => NULL,
                'wallet_ballance_before' => '0.00',
                'wallet_ballance_after' => '0.00',
                'wallet_cash_in' => '0.00',
                'wallet_cash_out' => '0.00',
                'wallet_user_from' => 0,
                'wallet_user_from_name' => NULL,
                'wallet_note' => 'Created by registration',
                'wallet_pajak' => '0.00',
                'wallet_id_grade_pajak' => 0,
                'wallet_id_referensi' => 0,
                'created_at' => '2019-01-15 03:22:10',
                'updated_at' => '2019-01-15 03:22:10',
            ),
            1 => 
            array (
                'id' => 2,
                'wallet_type_log' => 'created',
                'wallet_type' => 2,
                'wallet_user_id' => 1,
                'wallet_user_name' => NULL,
                'wallet_ballance_before' => '0.00',
                'wallet_ballance_after' => '0.00',
                'wallet_cash_in' => '0.00',
                'wallet_cash_out' => '0.00',
                'wallet_user_from' => 0,
                'wallet_user_from_name' => NULL,
                'wallet_note' => 'Created by registration',
                'wallet_pajak' => '0.00',
                'wallet_id_grade_pajak' => 0,
                'wallet_id_referensi' => 0,
                'created_at' => '2019-01-15 03:22:10',
                'updated_at' => '2019-01-15 03:22:10',
            ),
            2 => 
            array (
                'id' => 3,
                'wallet_type_log' => 'created',
                'wallet_type' => 3,
                'wallet_user_id' => 1,
                'wallet_user_name' => NULL,
                'wallet_ballance_before' => '0.00',
                'wallet_ballance_after' => '0.00',
                'wallet_cash_in' => '0.00',
                'wallet_cash_out' => '0.00',
                'wallet_user_from' => 0,
                'wallet_user_from_name' => NULL,
                'wallet_note' => 'Created by registration',
                'wallet_pajak' => '0.00',
                'wallet_id_grade_pajak' => 0,
                'wallet_id_referensi' => 0,
                'created_at' => '2019-01-15 03:22:10',
                'updated_at' => '2019-01-15 03:22:10',
            ),
            3 => 
            array (
                'id' => 4,
                'wallet_type_log' => 'created',
                'wallet_type' => 4,
                'wallet_user_id' => 1,
                'wallet_user_name' => NULL,
                'wallet_ballance_before' => '0.00',
                'wallet_ballance_after' => '0.00',
                'wallet_cash_in' => '0.00',
                'wallet_cash_out' => '0.00',
                'wallet_user_from' => 0,
                'wallet_user_from_name' => NULL,
                'wallet_note' => 'Created by registration',
                'wallet_pajak' => '0.00',
                'wallet_id_grade_pajak' => 0,
                'wallet_id_referensi' => 0,
                'created_at' => '2019-01-15 03:22:10',
                'updated_at' => '2019-01-15 03:22:10',
            ),
            4 => 
            array (
                'id' => 5,
                'wallet_type_log' => 'created',
                'wallet_type' => 5,
                'wallet_user_id' => 1,
                'wallet_user_name' => NULL,
                'wallet_ballance_before' => '0.00',
                'wallet_ballance_after' => '0.00',
                'wallet_cash_in' => '0.00',
                'wallet_cash_out' => '0.00',
                'wallet_user_from' => 0,
                'wallet_user_from_name' => NULL,
                'wallet_note' => 'Created by registration',
                'wallet_pajak' => '0.00',
                'wallet_id_grade_pajak' => 0,
                'wallet_id_referensi' => 0,
                'created_at' => '2019-01-15 03:22:10',
                'updated_at' => '2019-01-15 03:22:10',
            ),
            5 => 
            array (
                'id' => 6,
                'wallet_type_log' => 'created',
                'wallet_type' => 1,
                'wallet_user_id' => 2,
                'wallet_user_name' => NULL,
                'wallet_ballance_before' => '0.00',
                'wallet_ballance_after' => '0.00',
                'wallet_cash_in' => '0.00',
                'wallet_cash_out' => '0.00',
                'wallet_user_from' => 0,
                'wallet_user_from_name' => NULL,
                'wallet_note' => 'Created by registration',
                'wallet_pajak' => '0.00',
                'wallet_id_grade_pajak' => 0,
                'wallet_id_referensi' => 0,
                'created_at' => '2019-01-15 03:40:48',
                'updated_at' => '2019-01-15 03:40:48',
            ),
            6 => 
            array (
                'id' => 7,
                'wallet_type_log' => 'created',
                'wallet_type' => 2,
                'wallet_user_id' => 2,
                'wallet_user_name' => NULL,
                'wallet_ballance_before' => '0.00',
                'wallet_ballance_after' => '0.00',
                'wallet_cash_in' => '0.00',
                'wallet_cash_out' => '0.00',
                'wallet_user_from' => 0,
                'wallet_user_from_name' => NULL,
                'wallet_note' => 'Created by registration',
                'wallet_pajak' => '0.00',
                'wallet_id_grade_pajak' => 0,
                'wallet_id_referensi' => 0,
                'created_at' => '2019-01-15 03:40:48',
                'updated_at' => '2019-01-15 03:40:48',
            ),
            7 => 
            array (
                'id' => 8,
                'wallet_type_log' => 'created',
                'wallet_type' => 3,
                'wallet_user_id' => 2,
                'wallet_user_name' => NULL,
                'wallet_ballance_before' => '0.00',
                'wallet_ballance_after' => '0.00',
                'wallet_cash_in' => '0.00',
                'wallet_cash_out' => '0.00',
                'wallet_user_from' => 0,
                'wallet_user_from_name' => NULL,
                'wallet_note' => 'Created by registration',
                'wallet_pajak' => '0.00',
                'wallet_id_grade_pajak' => 0,
                'wallet_id_referensi' => 0,
                'created_at' => '2019-01-15 03:40:48',
                'updated_at' => '2019-01-15 03:40:48',
            ),
            8 => 
            array (
                'id' => 9,
                'wallet_type_log' => 'created',
                'wallet_type' => 4,
                'wallet_user_id' => 2,
                'wallet_user_name' => NULL,
                'wallet_ballance_before' => '0.00',
                'wallet_ballance_after' => '0.00',
                'wallet_cash_in' => '0.00',
                'wallet_cash_out' => '0.00',
                'wallet_user_from' => 0,
                'wallet_user_from_name' => NULL,
                'wallet_note' => 'Created by registration',
                'wallet_pajak' => '0.00',
                'wallet_id_grade_pajak' => 0,
                'wallet_id_referensi' => 0,
                'created_at' => '2019-01-15 03:40:48',
                'updated_at' => '2019-01-15 03:40:48',
            ),
            9 => 
            array (
                'id' => 10,
                'wallet_type_log' => 'created',
                'wallet_type' => 5,
                'wallet_user_id' => 2,
                'wallet_user_name' => NULL,
                'wallet_ballance_before' => '0.00',
                'wallet_ballance_after' => '0.00',
                'wallet_cash_in' => '0.00',
                'wallet_cash_out' => '0.00',
                'wallet_user_from' => 0,
                'wallet_user_from_name' => NULL,
                'wallet_note' => 'Created by registration',
                'wallet_pajak' => '0.00',
                'wallet_id_grade_pajak' => 0,
                'wallet_id_referensi' => 0,
                'created_at' => '2019-01-15 03:40:48',
                'updated_at' => '2019-01-15 03:40:48',
            ),
            10 => 
            array (
                'id' => 11,
                'wallet_type_log' => 'created',
                'wallet_type' => 1,
                'wallet_user_id' => 3,
                'wallet_user_name' => NULL,
                'wallet_ballance_before' => '0.00',
                'wallet_ballance_after' => '0.00',
                'wallet_cash_in' => '0.00',
                'wallet_cash_out' => '0.00',
                'wallet_user_from' => 0,
                'wallet_user_from_name' => NULL,
                'wallet_note' => 'Created by registration',
                'wallet_pajak' => '0.00',
                'wallet_id_grade_pajak' => 0,
                'wallet_id_referensi' => 0,
                'created_at' => '2019-01-15 03:55:54',
                'updated_at' => '2019-01-15 03:55:54',
            ),
            11 => 
            array (
                'id' => 12,
                'wallet_type_log' => 'created',
                'wallet_type' => 2,
                'wallet_user_id' => 3,
                'wallet_user_name' => NULL,
                'wallet_ballance_before' => '0.00',
                'wallet_ballance_after' => '0.00',
                'wallet_cash_in' => '0.00',
                'wallet_cash_out' => '0.00',
                'wallet_user_from' => 0,
                'wallet_user_from_name' => NULL,
                'wallet_note' => 'Created by registration',
                'wallet_pajak' => '0.00',
                'wallet_id_grade_pajak' => 0,
                'wallet_id_referensi' => 0,
                'created_at' => '2019-01-15 03:55:54',
                'updated_at' => '2019-01-15 03:55:54',
            ),
            12 => 
            array (
                'id' => 13,
                'wallet_type_log' => 'created',
                'wallet_type' => 3,
                'wallet_user_id' => 3,
                'wallet_user_name' => NULL,
                'wallet_ballance_before' => '0.00',
                'wallet_ballance_after' => '0.00',
                'wallet_cash_in' => '0.00',
                'wallet_cash_out' => '0.00',
                'wallet_user_from' => 0,
                'wallet_user_from_name' => NULL,
                'wallet_note' => 'Created by registration',
                'wallet_pajak' => '0.00',
                'wallet_id_grade_pajak' => 0,
                'wallet_id_referensi' => 0,
                'created_at' => '2019-01-15 03:55:54',
                'updated_at' => '2019-01-15 03:55:54',
            ),
            13 => 
            array (
                'id' => 14,
                'wallet_type_log' => 'created',
                'wallet_type' => 4,
                'wallet_user_id' => 3,
                'wallet_user_name' => NULL,
                'wallet_ballance_before' => '0.00',
                'wallet_ballance_after' => '0.00',
                'wallet_cash_in' => '0.00',
                'wallet_cash_out' => '0.00',
                'wallet_user_from' => 0,
                'wallet_user_from_name' => NULL,
                'wallet_note' => 'Created by registration',
                'wallet_pajak' => '0.00',
                'wallet_id_grade_pajak' => 0,
                'wallet_id_referensi' => 0,
                'created_at' => '2019-01-15 03:55:54',
                'updated_at' => '2019-01-15 03:55:54',
            ),
            14 => 
            array (
                'id' => 15,
                'wallet_type_log' => 'created',
                'wallet_type' => 5,
                'wallet_user_id' => 3,
                'wallet_user_name' => NULL,
                'wallet_ballance_before' => '0.00',
                'wallet_ballance_after' => '0.00',
                'wallet_cash_in' => '0.00',
                'wallet_cash_out' => '0.00',
                'wallet_user_from' => 0,
                'wallet_user_from_name' => NULL,
                'wallet_note' => 'Created by registration',
                'wallet_pajak' => '0.00',
                'wallet_id_grade_pajak' => 0,
                'wallet_id_referensi' => 0,
                'created_at' => '2019-01-15 03:55:54',
                'updated_at' => '2019-01-15 03:55:54',
            ),
        ));
        
        
    }
}